- name: Instalando Pré-Requisitos
  hosts: local
  become: yes
  tasks:
  - name: Instalar o Git
    apt:
      name: git-core, git-gui, git-doc

  - name: Instala Aptitude
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Instala os pacotes de sistemas necessários
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Adiciona o Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Adiciona o repositório do docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Atualiza o apt e instala o docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  
  - name: Instala do python-pip
    apt: name=python-pip

  - name: Instala o módulo do Docker para Python
    pip:
      name: docker-py
  
  - name: Adiciona a imagem itzg/minecraft-server
    docker_image:
      name: "itzg/minecraft-server"
      source: pull  
